project:
  type: website

website:
  title: "robot-physicist-website"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: charts/index.qmd
        text: Charts
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - morph
      - brand
    css: styles.css
    toc: true



